"""
This is a setup.py script generated by py2applet


Installation on my Mac:
    From within PyCharme (already activated venv) I run:
    python setup.py py2app
    zip -r dist/ReDict.zip dist/Redict.app
    mv dist/ReDict.zip /Users/retowietlisbach/OneDrive/013_Python/Redict/Mac/Redict.zip

Installation on my Windows
    from within Pycharme (already activated venv) I run:
    pyinstaller.bat

Installation for Linux (on Windows with WSL

reto@CRE-NB-25:/mnt/c/Workspace/ReDict/dist_linux$ pyinstaller -w -F --onefile --icon=../src/_gui/icons/icon.ico --hidden-import pkg_resources.py2_warn ../src/ReDict.py
"""

from setuptools import setup, find_packages

APP = ['src/ReDict.py']
DATA_FILES = [
    ('_gui', ['src/_gui/about.ui',
             'src/_gui/history.ui',
             'src/_gui/lookup.ui',
             'src/_gui/main.ui',
             'src/_gui/icons/icon.png',
             'src/_gui/settings.ui',
            ]
     ),
    ('_database', ['src/_database/redict.db']),
    ('_gui/stylesheets', ['src/_gui/stylesheets/AMOLED.qss',
                          'src/_gui/stylesheets/Aqua.qss',
                          'src/_gui/stylesheets/ConsoleStyle.qss',
                          'src/_gui/stylesheets/Dark.qss',
                          'src/_gui/stylesheets/ManjaroMix.qss',
                          'src/_gui/stylesheets/MaterialDark.qss',
                          'src/_gui/stylesheets/Ubuntu.qss',
                          ])
]
OPTIONS = {'iconfile': 'src/_gui/icons/icon.icns'}
print(find_packages(''))
setup(
    name = 'Redict',
    version = '0.0.2',
    author = 'Reto Wietlisbach',
    author_email = 'rwietlisbach@hotmail.com',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    packages=find_packages(''),
    setup_requires=['py2app', 'setuptools', 'PyQt5', 'bs4', 'cltk',
                    'lxml', 'Python-Levenshtein', 'PyStarDict', 'tqdm']
)