"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
    mv dist/Redict.app /Users/retowietlisbach/OneDrive/013_Python/Redict/Mac/Redict.app
"""

from setuptools import setup, find_packages

APP = ['src/ReDict.py']
DATA_FILES = [
    ('_gui', ['src/_gui/about.ui',
             'src/_gui/history.ui',
             'src/_gui/lookup.ui',
             'src/_gui/main.ui',
             'src/_gui/icons/icon.png',
             'src/_gui/settings.ui',
            ]
     ),
    ('_database', ['src/_database/redict.db']),
    ('_gui/stylesheets', ['src/_gui/stylesheets/AMOLED.qss',
                          'src/_gui/stylesheets/Aqua.qss',
                          'src/_gui/stylesheets/ConsoleStyle.qss',
                          'src/_gui/stylesheets/Dark.qss',
                          'src/_gui/stylesheets/ManjaroMix.qss',
                          'src/_gui/stylesheets/MaterialDark.qss',
                          'src/_gui/stylesheets/Ubuntu.qss',
                          ])
]
OPTIONS = {'iconfile': 'src/_gui/icons/icon.icns'}
print(find_packages(''))
setup(
    name = 'Redict',
    version = '0.0.2',
    author = 'Reto Wietlisbach',
    author_email = 'rwietlisbach@hotmail.com',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    packages=find_packages(''),
    setup_requires=['py2app', 'setuptools', 'PyQt5', 'bs4', 'cltk',
                    'lxml', 'Python-Levenshtein', 'PyStarDict', 'tqdm']
)