"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Redict.py']
DATA_FILES = [
    ('_gui', ['_gui/about.ui',
             '_gui/history.ui',
             '_gui/lookup.ui',
             '_gui/main.ui',
             '_gui/icon.png',
             '_gui/tbZoomOut.png',
             '_gui/tbZoomIn.png',
             '_gui/tbQuit.png',
             '_gui/tbLookup.png',
             '_gui/tbHistory.png',
             '_gui/tbCompleter.png',
             '_gui/tbAbout.png']
     ),
    ('_gui/stylesheets', ['_gui/stylesheets/AMOLED.qss']),
    ('_database', ['_database/dictionaries_db.db'])
]
OPTIONS = {'iconfile': '_gui/icon.icns'}

setup(
    name = 'Redict',
    version = '0.0.1',
    author = 'Reto Wietlisbach',
    author_email = 'rwietlisbach@hotmail.com',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'setuptools', 'PyQt5', 'pyperclip', 'bs4']
)
