"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages

APP = ['ReDict.py']
DATA_FILES = [
    ('_gui', ['_gui/about.ui',
             '_gui/history.ui',
             '_gui/lookup.ui',
             '_gui/main.ui',
             '_gui/icons/icon.png',
             '_gui/settings.ui',
            ]
     ),
    ('_database', ['_database/redict.db']),
    ('_gui/stylesheets', ['_gui/stylesheets/AMOLED.qss',
                          '_gui/stylesheets/Aqua.qss',
                          '_gui/stylesheets/ConsoleStyle.qss',
                          '_gui/stylesheets/Dark.qss',
                          '_gui/stylesheets/ManjaroMix.qss',
                          '_gui/stylesheets/MaterialDark.qss',
                          '_gui/stylesheets/Ubuntu.qss',
                          ])
]
OPTIONS = {'iconfile': '_gui/icons/icon.icns'}

setup(
    name = 'Redict',
    version = '0.0.2',
    author = 'Reto Wietlisbach',
    author_email = 'rwietlisbach@hotmail.com',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    packages=find_packages(),
    setup_requires=['py2app', 'setuptools', 'PyQt5', 'bs4', 'cltk',
                    'lxml', 'Python-Levenshtein', 'PyStarDict', 'tqdm']
)
